refactor: ajusta inclusão da tag no build

diff --git a/.github/workflows/packaging-and-publishing.yml b/.github/workflows/packaging-and-publishing.yml
--- a/.github/workflows/packaging-and-publishing.yml
+++ b/.github/workflows/packaging-and-publishing.yml
@@ -20,9 +20,15 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Extract tag from GITHUB_REF_NAME
+      - name: Extract tag from semantic release
         id: extract-tag
-        run: echo "::set-output name=tag::${GITHUB_REF_NAME}"
+        run: |
+          TAG=$(echo "${GITHUB_REF_NAME}" | grep -Eo "v[0-9]+\.[0-9]+\.[0-9]+")
+          if [ -z "$TAG" ]; then
+            echo "::error::No valid semantic version tag found."
+            exit 1
+          fi
+          echo "::set-output name=tag::$TAG"
 
       - name: Build Docker image
         run: |
